version: "3"
services:
  listings-svc:
    build: "./listings-svc"
    depends_on:
      - listings-svc-db
    environment:
      - DB_URL=mysql://root:VQTmFnwGbO@listings-svc-db/db?charset=UTF8
    ports:
      - 7100:7100
    volumes:
      - ./listings-svc:/opt/app
  listings-svc-db:
    environment:
      - MYSQL_ROOT_PASSWORD=VQTmFnwGbO
      - MYSQL_DATABASE=db
    image: mysql:5.7.20
    ports:
      - 0.0.0.0:7200:3306

  users-svc:
    build: "./users-svc"
    depends_on:
      - users-svc-db
    environment:
      - DB_URL=mysql://root:VQTnFnwGbO@users-svc-db/db?charset=UTF8
    ports:
      - 7101:7101
    volumes:
      - ./users-svc:/opt/app

  users-svc-db:
    environment:
      - MYSQL_ROOT_PASSWORD=VQTnFnwGbO
      - MYSQL_DATABASE=db
    image: mysql:5.7.20
    ports:
      - 0.0.0.0:7201:3306
